In [1]:
import torch

In [4]:
torch.zeros((2,2,3))

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

In [9]:
a = torch.arange(6).reshape((2, 3))
b = torch.arange(12).reshape((2, 2, 3))
a+b

tensor([[[ 0,  2,  4],
         [ 6,  8, 10]],

        [[ 6,  8, 10],
         [12, 14, 16]]])

In [16]:
a[1]

tensor([3, 4, 5])